# Generated by Django 5.1.3 on 2024-12-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={
                'verbose_name': 'Categoría de Productos',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
