# Generated by Django 5.1.3 on 2024-12-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('producto', '0002_alter_categoria_options_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
